spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cafe
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #system.out으로 찍음
        #show_sql: ture
        format_sql: true
logging:
  level:
  #logger로 찍음
    org.hibernate.SQL: debug
    org.hibernate.type: trace
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json